StatusApp/urls.py
from django.urls import path, include

from . import views

app_name = "status"
urlpatterns = [
    path("", views.GroupListView.as_view(), name="group_list"),
    path("group/", views.GroupListView.as_view(), name="sb-default"),
    path("group/add/", views.CreateGroup, name="sb-group-create"),
    path("group/<slug:slug>/", views.GroupMembersList, name="sb-group-view"),
    path(
        "group/<slug:slug>/mod/<slug:user>/<str:action>",
        views.GroupCRUD,
        name="sb-group-crud",
    ),
    path("group/<slug:slug>/mod", views.GroupModView, name="sb-group-mod"),
    path("group/<slug:slug>/user/search", views.UserSearch, name="user-search"),
    path("user/search/", views.UserStatusSearch, name="user-status-search"),
    path("userstatus/modal/<slug:slug>", views.UserStatusModal, name="user-modal"),
    path("members/<slug:slug>/", views.LoadGroupMembers, name="sb-group-members"),
]

StatusBoard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("StatusApp.urls")),
    path("accounts/", include("allauth.urls")),
]

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
{% load django_htmx %}
{% load i18n %}
{% load status_tags %}

{% get_current_language as LANGUAGE_CODE %}
{% bootstrap_setting "color_mode" as COLOR_MODE %}
{% bootstrap_setting "javascript_in_head" as BOOTSTRAP_JAVASCRIPT_IN_HEAD %}
{% bootstrap_setting "theme_url" as THEME %}
<html lang="{{ LANGUAGE_CODE|default:'en_us' }}"{% if COLOR_MODE %} data-bs-theme="{{ COLOR_MODE }}"{% endif %}>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Page title -->
    <title>{% block pagetitle %}template title{% endblock %}</title>
    <!-- Bootstrap CSS -->
     {% if THEME %}
       <link rel="stylesheet" href="{{THEME}}">
      {%else %}
        <link rel="stylesheet" href="{% static 'centraloffice/css/bootstrap.min.css' %}">
      {%endif%}
    <!-- Bootstrap JavaScript if it is in head -->
    {% if BOOTSTRAP_JAVASCRIPT_IN_HEAD %}<script src="{% static 'centraloffice/js/bootstrap.bundle.min.js' %}"></script>{% endif %}
    {% htmx_script %}
  {% block head %}{% endblock %}
</head>

<body>
{% block before_content %}


{% endblock %}
{% include "topbar.html" %}
<div id="wrapper" class="row">

  <div class="col-2">
    {% include "sidebar.html" %}
  </div>

  <div class="col-10">
    <div class="continer-fluid">
      {%block content %}CONTENT{%endblock%}
    </div>
  </div>
</div>

{% status_modal_target %}



{% block after_content %}{% endblock %}
<!-- Bootstrap JavaScript if it is in body -->
{% if not BOOTSTRAP_JAVASCRIPT_IN_HEAD %}<script src="{% static 'centraloffice/js/bootstrap.bundle.min.js' %}"></script>{% endif %}

{% block extra_script %}{% endblock %}
</body>

</html>

templates/sidebar.html
    <!-- Sidebar col-md-3 col-lg-2   -->
    <nav id="sidebarMenu" class="d-md-block sidebar collapse">
      <div class="position-sticky">
        <ul class="nav flex-column">
          {% for item in main_menu %}
             
            {% if item.children %}
              <li class="nav-item">
                <a class="nav-link d-flex align-items-center" data-bs-toggle="collapse" href="#submenu{{ forloop.counter }}" role="button" aria-expanded="false" aria-controls="submenu{{ forloop.counter }}">
                  {% if item.icon %}<i class="bi {{ item.icon }} me-2"></i>{% endif %}
                  {{ item.label }}
                  <i class="bi bi-caret-down-fill ms-auto small"></i>
                </a>
                <div class="collapse" id="submenu{{ forloop.counter }}">
                  <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small ms-3">
                    {% for child in item.children %}
                      <li>
                        <a class="nav-link" href="{% url child.url_name %}">
                          {% if child.icon %}<i class="bi {{ child.icon }} me-1"></i>{% endif %}
                          {{ child.label }}
                        </a>
                      </li>
                    {% endfor %}
                  </ul>
                </div>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link d-flex align-items-center" href="{% url item.url_name %}">
                  {% if item.icon %}<i class="bi {{ item.icon }} me-2"></i>{% endif %}
                  {{ item.label }}
                </a>
              </li>
            {% endif %}
          {% endfor %}
        </ul>
      </div>
    </nav>

templates/topbar.html
{% load static %}
{% load django_bootstrap5 %}
{% load i18n %}
{% load account %}
{% load status_tags %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Status Board</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {%block topnavmenu %}
      {%endblock%}
      {% if user.is_authenticated %}
      <div class="d-flex ms-auto me-3 position-relative">
        <input
          id="user-search-input"
          class="form-control form-control-sm"
          type="search"
          name="q"
          placeholder="Search users"
          aria-label="Search users"
          autocomplete="off"
          hx-get="{% url 'status:user-status-search' %}"
          hx-trigger="keyup changed delay:300ms"
          hx-target="#user-search-results"
        />
        <div id="user-search-results" class="position-absolute top-100 start-0 mt-1 w-100"></div>
      </div>
      {% endif %}
        <ul class="navbar-nav me-2 mb-lg-0 ">
      {% if user.is_authenticated %}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{user.first_name}} {{user.last_name}} ({{user.username}})
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li><a class="dropdown-item" 
                           hx-target="#set_status" 
                           hx-get="{% url 'status:user-modal' slug=user.slug %}"
                           data-bs-toggle="modal"
                           data-bs-target="#set_status">Status ({{user.status.status}})</a></li>
                    
                    {% if user.is_staff %}
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'admin:index' %}">Site Admin</a></li>
                    {%endif%}
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign Out</a></li>
                </ul>
            </li>

      {%else%}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account_login' %}">Sign In</a>
      </li>
      {%endif%}
    </ul>

    </div>
</nav>